[package]
name = "lgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { version = "23.0.0", features = [
	"wgsl",
	"webgl",
	"vulkan-portability",
	"metal",
] }
env_logger = "0.11.5"
log = "0.4.22"
pollster = "0.4.0"
serde = "1.0.214"
serde_json = "1.0.132"
thiserror = "2.0.1"
winit = { version = "0.29", features = ["rwh_05", "serde"] }
cfg-if = "1.0.0"
wgpu-hal = "23.0.0"
bytemuck = "1.19.0"
