[package]
name = "lgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
serde = "1.0.214"
serde_json = "1.0.132"
thiserror = "2.0.1"
wgpu = "23.0.0"
winit = { version = "0.29", features = ["rwh_05", "serde", "wayland"] }
